# Generated by notebook-2-app @ 2024-06-01 13:48:36.050992
# Based on notebook /Workspace/Users/ben.mullan@((redacted)).co.uk/notebook-2-app/scatter-bar-line

import pandas, numpy, plotly.express

dataFrame = pandas.DataFrame({"x": numpy.random.rand(20), "y": numpy.random.rand(20)})

# Make API request to get sensitive-data...
# (This is not a real API key)
api_key = "dbapi_938c2cc0dcc05f2b68c4287040cfcf71"


# Replaced <figure>.show() with Dash Server.
# ⚠ Have only one Dash server per application.

import dash;
app = dash.Dash(__name__);
app.layout = dash.html.Div(
    [
        dash.dcc.Markdown('**Application Title Here**'),
        dash.dcc.Graph(figure=figure1)
    ]
);
if __name__ == '__main__': app.run(debug=False);

figure1.show()
