# Generated by notebook-2-app @ 2024-06-24 22:34:32.976982
# Based on notebook /Workspace/Users/ben.mullan@ ((redacted)) .co.uk/notebook-2-app-res/n2a-workspace-file-demo

import pandas, plotly.express

# Make API request to get sensitive-data...
api_key = "dbapi_938c2cc0dcc05f2b68c4287040cfcf71"

po2_dataframe = pandas.read_csv(
    "/Workspace/Users/ben.mullan@ ((redacted)) .co.uk/powers-of-two.csv"
)

po2_line = plotly.express.line(po2_dataframe, x="x", y="y")
po2_line.show()
